# Spring properties
spring:
  application:
    name: web-service  # Identify this application
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/web-server/templates/    # Trailing / mandatory
                       # Template location for this application only

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

service:
  accounts:
    url: accounts.cf.ns.nd-paas.itn.ftgroup